const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const {Store,mergeEntry}=require('../src/store.cjs');const {rows,exportWorkbook}=require('../src/export.cjs');const ExcelJS=require('exceljs');
function entry(){return {source:'mw',headword:'example',url:'https://www.merriam-webster.com/dictionary/example',senses:[{pos:'noun',section:'1',definition:'a pattern',translation:'',selected:true,examples:[{text:'an example',translation:'',selected:true},{text:'another example',translation:'',selected:true}]}],pronunciations:[{region:'MW 原始标音',value:'ig-ˈzam-pəl'}],audio:[],snapshot:[],warnings:[],forms:[],phrases:[],labels:[]};}
test('duplicate collection shares one record and preserves personal edits, source selection, groups and example choices',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-test-'));const store=new Store(root);let w=store.collect(entry());w.groups=['reading','exam'];w.notes='my note';w.entries.mw.senses[0].editedDefinition='my definition';w.entries.mw.senses[0].selected=false;w.entries.mw.senses[0].examples[1].selected=false;store.update(w);store.collect(entry());assert.equal(store.data.words.length,1);w=store.data.words[0];assert.equal(w.notes,'my note');assert.deepEqual(w.groups,['reading','exam']);assert.equal(w.entries.mw.senses[0].editedDefinition,'my definition');assert.equal(w.entries.mw.senses[0].selected,false);assert.equal(w.entries.mw.senses[0].examples[1].selected,false);assert.equal(new Store(root).data.words[0].notes,'my note');});
test('changed definitions preserve unmatched edits for explicit review',()=>{const old=entry();old.senses[0].editedTranslation='自己的译文';const incoming=entry();incoming.senses[0].definition='a changed pattern';const merged=mergeEntry(old,incoming);assert.equal(merged.review.length,1);assert.equal(merged.review[0].editedTranslation,'自己的译文');assert.equal(merged.senses[0].selected,false);});
test('source-aware example filtering, literal formula-like notes and requested field order survive XLSX roundtrip',async()=>{const mw=entry();const cam=entry();cam.source='cambridge';cam.senses[0].definition='Cambridge definition';cam.senses[0].translation='剑桥释义';cam.senses[0].examples[1].selected=false;const w={word:'example',source:'cambridge',entries:{mw,cambridge:cam},notes:'=1+1',createdAt:'2026-09-20T00:00:00Z'};const row=rows([w],'time')[0];assert.match(row.definition,/Cambridge/);assert.doesNotMatch(row.examples.split('\n\n')[1],/another/);assert.match(row.examples.split('\n\n')[0],/another/);assert.equal(row.us,'');const file=path.join(fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-xlsx-')),'test.xlsx');await exportWorkbook([w],['notes','word','definition'],'time',file);const wb=new ExcelJS.Workbook();await wb.xlsx.readFile(file);assert.equal(wb.worksheets[0].getCell('A2').value,'=1+1');assert.equal(wb.worksheets[0].getCell('B2').value,'example');assert.match(wb.worksheets[0].getCell('C2').value,/Cambridge/);});
test('random ordering keeps every word exactly once and asset paths cannot escape library',()=>{const list=Array.from({length:30},(_,i)=>({word:String(i),source:'mw',entries:{mw:entry()},createdAt:String(i),notes:''}));assert.deepEqual(rows(list,'random').map(w=>w.word).sort(),list.map(w=>w.word).sort());const store=new Store(fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-path-')));assert.throws(()=>store.asset('../outside'));assert.throws(()=>store.asset('C:\\Windows\\win.ini'));});
test('new collections start empty; saved selections and groups survive new definitions and reopening',()=>{
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-selection-')),store=new Store(root);
  let w=store.collect(entry());assert.equal(w.entries.mw.senses[0].selected,false);
  w.entries.mw.senses[0].selected=true;w.groups=['A','B'];store.update(w);
  const next=entry();next.senses.push({...structuredClone(next.senses[0]),definition:'a second definition'});
  w=store.collect(next);assert.deepEqual(w.entries.mw.senses.map(s=>s.selected),[true,false]);
  const loaded=new Store(root);assert.deepEqual(loaded.data.words[0].groups,['A','B']);
  const exported=rows(loaded.data.words,'time')[0];assert.match(exported.definition,/a pattern/);assert.doesNotMatch(exported.definition,/second/);
});
test('selected child definitions keep essential parent context in review and export',()=>{
  const {senseContext}=require('../src/ui/sense-context.js');const e=entry();
  e.senses[0].section='主词典 2';e.senses[0].selected=false;
  e.senses.push({...structuredClone(e.senses[0]),section:'主词典 2 also',definition:'an individual so punished',selected:true});
  assert.equal(senseContext(e.senses,1),'a pattern');
  const exported=rows([{word:'example',source:'mw',entries:{mw:e},createdAt:'2026-01-01',notes:''}],'time')[0];
  assert.match(exported.definition,/a pattern/);assert.match(exported.definition,/an individual so punished/);
});
