const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let settingsOrigin=null;
let data,fieldNames,root,page='search',activeId=null,browsing=false,toastTimer,columnOrder=[],columnSelected=new Set(),saveQueue=Promise.resolve();
const api=(method,...args)=>window.desk.invoke(method,...args);
function toast(message){$('#toast').textContent=message;$('#toast').classList.remove('hidden');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.add('hidden'),7500);}
async function run(fn){try{return await fn();}catch(e){toast(e.message.replace(/^Error invoking remote method 'desk': Error: /,''));}}
async function refresh(){const state=await api('init');if(root&&root!==state.root){for(const doc of workDocuments.values())doc.frame.remove();workDocuments.clear();workQueryOrigin=null;workTab='query';workLastPDF=null;closePDFPopup();}data=state.data;root=state.root;fieldNames=state.fields;$('#count').textContent=data.words.length;$('#storage-path').textContent=root;updateCollectionLabels();applyBehaviorPreferences(state);applyAppearance(state.appearance);applyWordSize(state.fontSize||18);}
function layout(){const b={};for(const s of ['mw','cambridge']){const r=$('#browser-'+s).getBoundingClientRect();b[s]={x:r.x,y:r.y,width:r.width,height:r.height};}api('layout',b,(page==='search'||(page==='work'&&workTab==='query'))&&browsing&&!collectionDialogBusy&&!document.querySelector('dialog[open]')).catch(()=>{});}
async function go(next){if(next!==page)interruptCollection();if(next==='work'&&page==='work'){syncWorkLayout();layout();return true;}const preserveDraft=next==='settings'||(page==='settings'&&next===settingsOrigin);if(!preserveDraft&&!await leaveSelection())return false;if(next==='settings'&&page!=='settings')settingsOrigin=page;rememberWorkLibraryScroll();await saveQueue;if(next!=='work'&&workFull)await setWorkFullscreen(false);if(next==='review'&&page!=='review')reviewPhoneticsVisible=false;page=next;$$('.page').forEach(e=>e.classList.toggle('hidden',e.id!=='page-'+(next==='review'?'library':next)));$$('[data-page]').forEach(e=>e.classList.toggle('active',e.dataset.page===next));if(next==='library'||next==='review'){await refresh();$('#library-heading').textContent=next==='review'?'专注于你选中的释义。':'把遇见变成积累。';$('#library-eyebrow').textContent=next==='review'?'REVIEW YOUR WORDS':'YOUR COLLECTION';$('#new-group').classList.toggle('hidden',next==='review');renderLibrary();detailScroller().scrollTop=0;}syncWorkLayout();if(next==='work'){await refresh();configureLibraryHeader();renderLibrary();workLibraryReady=true;if(workTab==='library')restoreWorkLibraryScroll();}if(next==='exam'){await refresh();renderExam();}if(next==='export'){await refresh();renderExport();}if(next==='settings')await refresh();if(next==='storage'){await refresh();renderTrash();await renderScreenshotCleanup();await renderCambridgeAudioCleanup();}layout();return true;}
$$('[data-page]').forEach(b=>b.onclick=()=>run(()=>go(b.dataset.page)));
new ResizeObserver(layout).observe($('#browser-grid'));window.addEventListener('resize',layout);
let dragging=false;$('#splitter').addEventListener('pointerdown',e=>{dragging=true;$('#splitter').setPointerCapture(e.pointerId);});$('#splitter').addEventListener('pointermove',e=>{if(!dragging)return;const r=$('#browser-grid').getBoundingClientRect();const fraction=Math.max(.25,Math.min(.75,(e.clientX-r.left)/r.width));$('#browser-grid').style.gridTemplateColumns=`minmax(0,${fraction}fr) 10px minmax(0,${1-fraction}fr)`;layout();});$('#splitter').addEventListener('pointerup',()=>dragging=false);
$('#search-form').onsubmit=e=>{e.preventDefault();interruptCollection();run(async()=>{if(page==='work')workQueryOrigin=captureWorkOrigin();await api('search',$('#query').value);browsing=true;layout();});};
$$('[data-nav]').forEach(b=>b.onclick=()=>run(()=>api('navigate',...b.dataset.nav.split(':'))));
window.desk.onStatus(({source,message,collection})=>{if(!collection&&message==='正在加载…')interruptCollection();if(collection&&collectionTask){collectionTask.messages[source]=message;renderCollectionProgress();}$('#status-'+source).textContent=message;});
async function collect(source,groups){const buttons=[$('#collect-both'),...$$('[data-collect], [data-quick]')];buttons.forEach(b=>b.disabled=true);try{if(selectionDraft&&!await leaveSelection())return;await saveQueue;const task=collectionTask={origin:page,interrupted:false,messages:{},done:false};renderCollectionProgress();const results=await api('collect',source,groups);await refresh();task.done=true;const success=results.filter(r=>!r.error);if(success.length){const id=data.words.find(w=>w.word===success[0].word)?.id;task.id=id;if(!task.interrupted){if(page==='work')await openWorkLibraryWord(id,'full',autoSelectAfterCollect,true);else{activeId=id;await go('library');}}}task.messages=Object.fromEntries(results.map(r=>[r.source,r.error?'失败：'+r.error:'已保存 '+r.word+(r.warnings.length?'（部分内容需检查，可在词条中重试）':'')]));renderCollectionProgress();toast(results.map(r=>`${r.source==='mw'?'MW':'剑桥'}：${r.error||'已保存 '+r.word+(r.warnings.length?'（有待检查项目）':'')}`).join('\n'));}finally{if(collectionTask&&!collectionTask.done){collectionTask.done=true;collectionTask.messages.error='收藏未完成，请重试';renderCollectionProgress();}buttons.forEach(b=>b.disabled=false);}}
$('#collect-both').onclick=()=>run(()=>chooseCollection('both'));$$('[data-collect]').forEach(b=>b.onclick=()=>run(()=>chooseCollection(b.dataset.collect)));
function word(){return data.words.find(w=>w.id===activeId);}
function saveWord(){const snapshot=structuredClone(word());const pending=saveQueue.then(()=>api('update',snapshot));saveQueue=pending.catch(e=>toast('保存失败：'+e.message));return pending;}
function renderLibrary(){configureLibraryHeader();const filter=$('#group-filter').value;$('#group-filter').innerHTML='<option value="">全部分组</option>'+data.groups.map(g=>`<option value="${esc(g)}">${esc(g)}</option>`).join('');$('#group-filter').value=data.groups.includes(filter)?filter:'';renderList();renderDetail();}
function renderList(){renderWordList();}
$('#library-search').oninput=renderList;$('#group-filter').onchange=renderList;
$('#new-group').onclick=()=>run(async()=>{if(!await leaveSelection())return;renderDetail();$('#group-name').value='';$('#group-dialog').showModal();$('#group-name').focus();});
$('#group-dialog').addEventListener('close',()=>{if($('#group-dialog').returnValue==='ok')run(async()=>{const name=$('#group-name').value.trim();if(!name)return;await api('groups',[...data.groups,name]);await refresh();renderLibrary();});});
function exportWords(){const scope=$('#export-scope').value;if(scope==='group')return data.words.filter(w=>w.groups.includes($('#export-group').value));if(scope==='selected'){const ids=$$('[data-export-word]:checked').map(b=>b.dataset.exportWord);return data.words.filter(w=>ids.includes(w.id));}return data.words;}
function updateExportScope(){const scope=$('#export-scope').value;$('#export-group').classList.toggle('hidden',scope!=='group');$('#export-words').classList.toggle('hidden',scope!=='selected');const missing=exportWords().filter(w=>!selectedCount(w)).length;$('#export-count').textContent=`将导出 ${exportWords().length} 个单词${missing?'；其中 '+missing+' 个尚未选择释义，释义列将留空。':''}`;$ ('#export-button').disabled=!exportWords().length;}
function renderExport(){columnOrder=[...(data.exportFields||[]).filter(k=>Object.hasOwn(fieldNames,k)),...Object.keys(fieldNames).filter(k=>!data.exportFields?.includes(k))];columnSelected=new Set(data.exportFields||[]);$('#export-group').innerHTML=data.groups.map(g=>`<option value="${esc(g)}">${esc(g)}</option>`).join('');$('#export-words').innerHTML=data.words.map(w=>`<label><input type="checkbox" data-export-word="${w.id}" checked> ${esc(w.word)}</label>`).join('');$$('[data-export-word]').forEach(b=>b.onchange=updateExportScope);const saved=data.exportOptions||{};$('#export-scope').value=['all','group','selected'].includes(saved.scope)?saved.scope:'all';$('#export-order').value=['time','alpha','random'].includes(saved.order)?saved.order:'time';if(data.groups.includes(saved.group))$('#export-group').value=saved.group;if(saved.scope==='selected'&&Array.isArray(saved.ids))$$('[data-export-word]').forEach(b=>b.checked=saved.ids.includes(b.dataset.exportWord));renderFields();updateExportScope();}
function renderFields(){$('#export-print-hint').textContent=columnSelected.size>3?'列数较多，A4 竖向打印可能较拥挤，建议优先使用三列。':'正文 11 磅 · 单词 12 磅加粗 · 每页重复表头';$('#export-print-preset').onclick=()=>{columnSelected=new Set(['word','pos','meaning']);columnOrder=['word','pos','meaning',...Object.keys(fieldNames).filter(k=>!columnSelected.has(k))];renderFields();};$('#export-fields').innerHTML=columnOrder.map((k,i)=>`<div class="field-row"><input id="f-${k}" type="checkbox" data-field="${k}" ${columnSelected.has(k)?'checked':''}><label for="f-${k}">${esc(fieldNames[k])}</label><button data-move="${i}:-1" ${i===0?'disabled':''} title="上移">↑</button><button data-move="${i}:1" ${i===columnOrder.length-1?'disabled':''} title="下移">↓</button></div>`).join('');$$('[data-field]').forEach(b=>b.onchange=()=>{b.checked?columnSelected.add(b.dataset.field):columnSelected.delete(b.dataset.field);renderFields();});$$('[data-move]').forEach(b=>b.onclick=()=>{const[i,d]=b.dataset.move.split(':').map(Number);[columnOrder[i],columnOrder[i+d]]=[columnOrder[i+d],columnOrder[i]];renderFields();});}
$('#export-scope').onchange=updateExportScope;$('#export-group').onchange=updateExportScope;
$('#export-button').onclick=()=>run(async()=>{const file=await api('export',{ids:exportWords().map(w=>w.id),fields:columnOrder.filter(k=>columnSelected.has(k)),order:$('#export-order').value,scope:$('#export-scope').value,group:$('#export-group').value});if(file){await refresh();toast('已导出：'+file);}});
$('#backup').onclick=()=>run(async()=>{await saveQueue;const file=await api('backup');if(file)toast('已备份：'+file);});
$('#restore').onclick=()=>run(async()=>{await saveQueue;const location=await api('restore');if(location){activeId=null;await refresh();renderTrash();await renderScreenshotCleanup();await renderCambridgeAudioCleanup();toast('已恢复并切换词库：'+location);}});
$('#change-location').onclick=()=>run(async()=>{await saveQueue;const location=await api('location');if(location){await refresh();await renderScreenshotCleanup();await renderCambridgeAudioCleanup();toast('词库已复制到新位置');}});
bindManagement();bindPreferences();bindWork();bindWordSize();
run(async()=>{await refresh();layout();});

let collectionTask=null;
function interruptCollection(){if(collectionTask&&!collectionTask.done)collectionTask.interrupted=true;}
function renderCollectionProgress(){const t=collectionTask,el=$('#collection-progress');el.classList.toggle('hidden',!t);document.body.classList.toggle('collection-visible',!!t);if(!t){layout();return;}el.innerHTML='<strong>'+ (t.done?'收藏结果':'正在收藏…')+'</strong><div class="collection-lines">'+Object.entries(t.messages).map(([s,m])=>esc(s==='mw'?'MW':'Cam')+'：'+esc(m)).join('<br>')+'</div>'+(t.done&&t.id?'<button id="collection-view">查看词条 / 重试</button>':'')+(t.done?'<button id="collection-dismiss">关闭</button>':'');if($('#collection-dismiss'))$('#collection-dismiss').onclick=()=>{collectionTask=null;renderCollectionProgress();};if($('#collection-view'))$('#collection-view').onclick=()=>run(async()=>{if(!await leaveSelection())return;if(page==='work')await openWorkLibraryWord(t.id,'full',autoSelectAfterCollect,true);else{activeId=t.id;await go('library');}});layout();}
