(function(root){
  const entrySources=word=>['mw','cambridge'].filter(source=>word.entries[source]);
  const selectedSources=word=>entrySources(word).filter(source=>word.entries[source].senses.some(s=>s.selected));
  const selectedCount=word=>entrySources(word).reduce((n,source)=>n+word.entries[source].senses.filter(s=>s.selected).length,0);
  // Existing Cambridge selections were bilingual before separate language choices existed.
  const includesChinese=sense=>!!sense.selected&&sense.includeChinese!==false;
  const hasPronunciation=entry=>!!entry&&(entry.pronunciationGroups?.some(g=>g.items?.some(p=>String(p.value||'').trim()))||entry.pronunciations?.some(p=>String(p.value||'').trim()));
  function reviewPronunciationSource(word){
    return hasPronunciation(word.entries.mw)?'mw':null;
  }
  // Cambridge's stored sequence numbers were generated by the parser, not the website.
  const dictionaryNumber=(sense,source)=>source==='cambridge'?'':String(sense.number||'').replace(/^—$/,'');
  const helpers={entrySources,selectedSources,selectedCount,includesChinese,reviewPronunciationSource,dictionaryNumber};
  if(typeof module!=='undefined'&&module.exports)module.exports=helpers;else Object.assign(root,helpers);
})(globalThis);
