const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{spawn}=require('node:child_process');
async function connect(url){const socket=new WebSocket(url);await new Promise((ok,no)=>{socket.onopen=ok;socket.onerror=no;});let id=0;const pending=new Map();socket.onmessage=e=>{const m=JSON.parse(e.data);if(pending.has(m.id)){const{ok,no,t}=pending.get(m.id);clearTimeout(t);pending.delete(m.id);m.error?no(new Error(JSON.stringify(m.error))):ok(m.result);}};return {close:()=>socket.close(),send:(method,params={})=>new Promise((ok,no)=>{const n=++id;const t=setTimeout(()=>{pending.delete(n);no(new Error('Timeout '+method));},45000);pending.set(n,{ok,no,t});socket.send(JSON.stringify({id:n,method,params}));})};}
async function evaluate(c,expression){const d=await c.send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true,includeCommandLineAPI:true});if(d.exceptionDetails)throw new Error(d.exceptionDetails.exception?.description||d.exceptionDetails.text);return d.result.value;}
(async()=>{const env={...process.env,WORDDESK_TEST_DATA:path.resolve('.package-check-data')};delete env.ELECTRON_RUN_AS_NODE;const child=spawn(path.resolve(`dist/WordDesk-${require('../package.json').version}-win32-x64/WordDesk.exe`),['--inspect=0','--remote-debugging-port=0'],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});let node,renderer;try{const endpoints=await new Promise((ok,no)=>{let log='';const t=setTimeout(()=>no(new Error(log)),30000);child.stderr.on('data',b=>{log+=b;const n=log.match(/Debugger listening on (ws:\/\/[^\s]+)/),c=log.match(/DevTools listening on (ws:\/\/[^\s]+)/);if(n&&c){clearTimeout(t);ok({node:n[1],browser:c[1]});}});child.on('error',no);});node=await connect(endpoints.node);await node.send('Runtime.enable');console.log('APP',await evaluate(node,"({ready:require('electron').app.isReady(),windows:require('electron').BrowserWindow.getAllWindows().map(w=>({title:w.getTitle(),visible:w.isVisible(),url:w.webContents.getURL()}))})"));
const base='http://'+new URL(endpoints.browser).host;const targets=await(await fetch(base+'/json/list')).json();console.log('TARGETS',targets.map(t=>[t.type,t.url]));const target=targets.find(t=>t.url.includes('/ui/index.html'));assert(target,'No application window');renderer=await connect(target.webSocketDebuggerUrl);await renderer.send('Runtime.enable');console.log('INIT',await evaluate(renderer,"window.desk.invoke('init').then(s=>({words:s.data.words.length,root:s.root}))"));
const parser=require('../src/extract.cjs').extractDictionary.toString();for(const[file,source]of [['parser-run-mw.html','mw'],['parser-run-cambridge.html','cambridge']]){const code=`(async()=>{const {BrowserWindow}=require('electron');const w=new BrowserWindow({show:false,webPreferences:{partition:'parse-test'}});w.webContents.session.webRequest.onBeforeRequest({urls:['http://*/*','https://*/*']},(d,cb)=>cb({cancel:true}));await w.loadFile(${JSON.stringify(path.resolve('fixtures',file))});try{return await w.webContents.executeJavaScript(${JSON.stringify(`(${parser})('${source}')`)});}finally{w.destroy();}})()`;const result=await evaluate(node,code);assert(result.senses.every(s=>s.pos));assert(result.pronunciations.length);if(source==='mw'){assert(result.senses.length>=204);assert(result.phrases.includes('at a run'));assert(result.senses.some(s=>s.section.includes('主词典 1 a')));}else assert(result.senses.some(s=>s.section.includes('GO QUICKLY')));console.log('PARSER',source,result.senses.length,result.phrases.length);}
await evaluate(renderer,"document.querySelector('#query').value='example'; document.querySelector('#search-form').requestSubmit(); true");await new Promise(r=>setTimeout(r,12000));console.log('LOOKUP READY');
const result=await evaluate(renderer,"window.desk.invoke('collect','both')");console.log('COLLECT',result);assert.equal(result.filter(r=>!r.error).length,2);const out=path.resolve('test/output/package-export.xlsx');await evaluate(node,`require('electron').dialog.showSaveDialog=async()=>({canceled:false,filePath:${JSON.stringify(out)}});true`);await evaluate(renderer,"window.desk.invoke('init').then(s=>window.desk.invoke('export',{ids:s.data.words.map(w=>w.id),fields:['word','definition','phonetic'],order:'random'}))");assert(fs.statSync(out).size>1000);console.log('PACKAGE PASSED');
}finally{if(node){await evaluate(node,"require('electron').app.quit();true").catch(()=>{});node.close();}renderer?.close();child.kill();}})().catch(e=>{console.error(e);process.exitCode=1;});
