const {_electron:electron}=require('playwright');
const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {Store}=require('../src/store.cjs');
const {rows}=require('../src/export.cjs');
(async()=>{
  const profile=fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-review-ui-'));
  const store=new Store(path.join(profile,'library'));
  const saved=JSON.parse(fs.readFileSync('fixtures/collected.json')).words[0];
  for(const e of Object.values(saved.entries))store.collect(structuredClone(e));
  const example=store.data.words[0];example.groups=['阅读','考试'];example.notes='My private note';
  store.collect(JSON.parse(fs.readFileSync('fixtures/beautiful-mw.json')));
  const legacy=store.data.words[1];legacy.entries.mw.senses[0].selected=true;legacy.groups=['阅读'];
  store.data.groups=['阅读','考试'];store.save();
  const env={...process.env,WORDDESK_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;
  const args=process.env.WORDDESK_RELEASE?[path.resolve(process.env.WORDDESK_RELEASE)]:['.'];
  let app=await electron.launch({args,env,timeout:30000});
  try{
    let page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
    await page.locator('[data-page="library"]').click();
    await page.locator(`.word-row[data-id="${example.id}"]`).click();
    assert.equal(await page.locator('[data-select-sense]').count(),0);
    assert.equal(await page.locator('.saved-sense').count(),0);
    await page.locator('#begin-selection').click();
    await page.locator('[data-select-sense="0"]').click();await page.locator('[data-select-sense="1"]').click();
    assert.equal((await page.evaluate(()=>window.desk.invoke('init'))).data.words[0].entries.mw.senses.filter(s=>s.selected).length,0);
    await page.locator('#cancel-selection').click();assert.equal(await page.locator('.saved-sense').count(),0);
    await page.locator('#begin-selection').click();await page.locator('[data-select-sense="0"]').click();await page.locator('[data-select-sense="2"]').click();
    await page.screenshot({path:'fixtures/ui-selection-v2.png'});
    await page.locator('[data-page="review"]').click();await page.locator('#selection-dialog').waitFor({state:'visible'});
    await page.locator('#selection-dialog button[value="continue"]').click();assert.equal(await page.locator('[data-select-sense]').count(),example.entries.mw.senses.length);
    await page.locator('[data-page="review"]').click();await page.locator('#selection-dialog button[value="save"]').click();
    await page.locator('.review-detail').waitFor();assert.equal(await page.locator('.dictionary-definition').count(),2);
    assert.equal(await page.locator('.personal-notes p').isVisible(),false);
    assert.equal(await page.locator('.review-extra .dictionary-example').first().isVisible(),false);
    assert.equal(await page.locator('.word-row').count(),2);
    await page.screenshot({path:'fixtures/ui-review-v2.png'});
    const after=await page.evaluate(()=>window.desk.invoke('init'));assert.equal(after.data.words[0].entries.mw.senses.filter(s=>s.selected).length,2);
    const exported=rows([after.data.words[0]],'time')[0];assert.match(exported.definition,new RegExp(example.entries.mw.senses[0].definition.slice(0,15)));
    assert(!exported.definition.includes(example.entries.mw.senses[3].definition));assert.equal(await page.locator('.sense-context').count(),1);
    await page.locator('#group-filter').selectOption('考试');assert.equal(await page.locator('.word-row').count(),1);
    await page.locator('#view-full').click();await page.locator('#begin-selection').click();await page.locator('[data-select-sense="1"]').click();
    await page.locator('[data-source="cambridge"]').click();await page.locator('#selection-dialog button[value="discard"]').click();
    assert.equal(await page.locator('.saved-sense').count(),0);
    await page.locator('[data-page="review"]').click();await page.locator('#choose-from-review').waitFor();
    await page.locator('#choose-from-review').click();await page.locator('[data-select-sense="0"]').focus();await page.keyboard.press('Space');await page.locator('#save-selection').click();
    await page.locator('[data-page="review"]').click();assert.equal(await page.locator('.dictionary-definition').count(),1);assert.equal(await page.locator('.dictionary-chinese').count(),1);
    await page.locator('#view-full').click();await page.locator('[data-source="mw"]').click();assert.equal(await page.locator('.saved-sense').count(),2);
    await page.screenshot({path:'fixtures/ui-library-v2.png'});
    // Closing follows the same save/discard/continue path as navigation.
    await page.locator('#begin-selection').click();await page.locator('[data-select-sense="1"]').click();
    await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].close();});
    await page.locator('#selection-dialog').waitFor();await page.locator('#selection-dialog button[value="continue"]').click();
    assert.equal(await page.locator('#save-selection').isVisible(),true);
    await page.locator('#cancel-selection').click();assert.deepEqual(errors,[]);
    await app.close();app=await electron.launch({args,env,timeout:30000});page=await app.firstWindow();
    await page.locator('[data-page="review"]').click();await page.locator(`.word-row[data-id="${example.id}"]`).click();
    assert.equal(await page.locator('.dictionary-definition').count(),2);
    const persisted=await page.evaluate(()=>window.desk.invoke('init'));assert.deepEqual(persisted.data.words[0].groups,['阅读','考试']);assert.equal(persisted.data.words[1].entries.mw.senses[0].selected,true);
    console.log('REVIEW UI PASSED: draft isolation, cancel, save, navigation guard, source choices, group sync, blank state, keyboard selection, close guard, restart persistence and export consistency.');
  }finally{await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
