const {_electron:electron}=require('playwright');const path=require('node:path');const fs=require('node:fs');const assert=require('node:assert/strict');
(async()=>{const env={...process.env,WORDDESK_TEST_DATA:path.resolve('.test-data')};delete env.ELECTRON_RUN_AS_NODE;const app=await electron.launch({args:['.'],env,timeout:60000});try{const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.waitForSelector('#query');await page.locator('#query').fill('example');await page.locator('#search-form').evaluate(f=>f.requestSubmit());
 await app.evaluate(async({webContents})=>{const end=Date.now()+45000;while(Date.now()<end){let n=0;for(const wc of webContents.getAllWebContents()){if(wc.getURL().startsWith('https:')){const ok=await wc.executeJavaScript('!!document.querySelector(".dtText, .def-block")').catch(()=>false);if(ok)n++;}}if(n===2)return;await new Promise(r=>setTimeout(r,500));}throw new Error('Dictionary content did not load');});
 const views=await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].contentView.children.map(v=>({bounds:v.getBounds(),visible:v.getVisible?.()})));console.log('Views',views);
 const screenshot=await app.evaluate(async({BrowserWindow})=>(await BrowserWindow.getAllWindows()[0].capturePage()).toPNG().toString('base64'));fs.writeFileSync('fixtures/ui-native.png',Buffer.from(screenshot,'base64'));
 const result=await page.evaluate(()=>window.desk.invoke('collect','both'));console.log('COLLECT',JSON.stringify(result));assert.equal(result.filter(x=>!x.error).length,2);
 const state=await page.evaluate(()=>window.desk.invoke('init'));fs.writeFileSync('fixtures/collected.json',JSON.stringify(state.data,null,2));const w=state.data.words.find(w=>w.word==='example');assert(w);for(const e of Object.values(w.entries)){assert(e.senses.length>0);assert(e.snapshot.length>0);assert(e.audio.some(a=>a.file));console.log(e.source,{senses:e.senses.length,phonetics:e.pronunciations,audio:e.audio.length,warnings:e.warnings});}
 await page.locator('[data-page="library"]').click();await page.locator('.word-row').first().click();await page.locator('#notes').fill('Smoke test note');await page.locator('#notes').blur();await page.waitForTimeout(400);await page.screenshot({path:'fixtures/ui-library.png'});
 await page.locator('[data-source="cambridge"]').click();await page.locator('#begin-selection').click();await page.locator('[data-select-sense="1"]').click();await page.locator('#save-selection').click();await page.locator('[data-page="export"]').click();await page.screenshot({path:'fixtures/ui-export.png'});
 const persisted=await page.evaluate(()=>window.desk.invoke('init'));assert.equal(persisted.data.words[0].notes,'Smoke test note');assert.equal(persisted.data.words[0].source,'cambridge');assert.equal(persisted.data.words[0].entries.cambridge.senses[0].selected,false);
 console.log('TRANSLATE',await page.evaluate(id=>window.desk.invoke('translate',id,'mw',0,null),w.id).catch(e=>'Unavailable: '+e.message));
 // Exercise native-dialog operations with deterministic destinations.
 const output=path.resolve('test/output');fs.mkdirSync(output,{recursive:true});await app.evaluate(({dialog},out)=>{dialog.showSaveDialog=async(_win,opt)=>({canceled:false,filePath:out+'/'+opt.defaultPath});},output);
 console.log('EXPORT',await page.evaluate(id=>window.desk.invoke('export',{ids:[id],fields:['word','definition','notes'],order:'random'}),w.id));
 const backup=await page.evaluate(()=>window.desk.invoke('backup'));console.log('BACKUP',backup);
 await app.evaluate(({dialog},{backup,output})=>{dialog.showOpenDialog=async(_win,opt)=>({canceled:false,filePaths:[opt.properties.includes('openFile')?backup:output]});},{backup,output});console.log('RESTORE',await page.evaluate(()=>window.desk.invoke('restore')));
 const restored=await page.evaluate(()=>window.desk.invoke('init'));assert.equal(restored.data.words[0].notes,'Smoke test note');assert.equal(restored.data.words[0].entries.cambridge.senses[0].selected,false);const file=restored.data.words[0].entries.cambridge.audio.find(a=>a.file).file;assert((await page.evaluate(f=>window.desk.invoke('audio',f),file)).startsWith('data:audio/mpeg;base64,'));assert.deepEqual(errors,[]);console.log('SMOKE PASSED');
}finally{await app.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
