const {_electron:electron}=require('playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {Store}=require('../src/store.cjs');
function makePDF(){const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R 5 0 R] /Count 2 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 850] /Resources << /Font << /F1 7 0 R >> >> /Contents 4 0 R >>',null,'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 600 850] /Resources << /Font << /F1 7 0 R >> >> /Contents 6 0 R >>',null,'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'];for(const [i,text]of [[3,'obscure'],[5,'navigation']]){const stream='BT /F1 24 Tf 60 760 Td ('+text+') Tj ET';objects[i]='<< /Length '+stream.length+' >>\nstream\n'+stream+'\nendstream';}let out='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(out.length);out+=(i+1)+' 0 obj\n'+o+'\nendobj\n';});const offset=out.length;out+='xref\n0 8\n0000000000 65535 f \n'+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+'trailer\n<< /Size 8 /Root 1 0 R >>\nstartxref\n'+offset+'\n%%EOF';return Buffer.from(out);}
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-v10-')),store=new Store(path.join(profile,'library'));store.data.groups=['阅读'];const w=store.collect(JSON.parse(fs.readFileSync('fixtures/go-mw-v3.json')),['阅读']);store.collect(JSON.parse(fs.readFileSync('fixtures/go-cambridge-v3.json')),['阅读']);w.entries.cambridge.senses[0].selected=true;store.save();const file=path.join(profile,'test.pdf');fs.writeFileSync(file,makePDF());
const env={...process.env,WORDDESK_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;const app=await electron.launch({args:process.env.WORDDESK_RELEASE?[path.resolve(process.env.WORDDESK_RELEASE)]:['.'],env,timeout:30000});let page;
try{page=await app.firstWindow();page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await app.evaluate(async({session})=>{for(const s of ['mw','cambridge'])await session.fromPartition('persist:dictionary-'+s).protocol.handle('https',()=>new Response('<h1>Test dictionary</h1>',{headers:{'content-type':'text/html'}}));});
await page.locator('[data-page="review"]').click();await page.locator('.word-row').click();await page.locator('#toggle-review-phonetics').click();assert.equal(await page.locator('[data-pron-source]').getAttribute('data-pron-source'),'mw');
await page.locator('[data-page="library"]').click();await page.locator('[data-source="cambridge"]').click();assert.doesNotMatch(await page.locator('.pronunciation-flow').innerText(),/英式|美式/);assert.match(await page.locator('.pronunciation-flow').innerText(),/UK/);
await page.locator('[data-page="work"]').click();assert(await page.locator('#page-work #query').isVisible());await page.locator('#work-files').setInputFiles(file);const frame=page.frameLocator('.work-pdf').first();await frame.locator('.textLayer span').filter({hasText:'obscure'}).waitFor();assert(await frame.locator('#sheet canvas').isVisible());
await frame.locator('#next').click();await frame.locator('.textLayer span').filter({hasText:'navigation'}).waitFor();await frame.locator('#zoom').selectOption('2');await frame.locator('.textLayer span').filter({hasText:'navigation'}).waitFor();await frame.locator('#scroller').evaluate(e=>e.scrollTop=200);const scroll=await frame.locator('#scroller').evaluate(e=>e.scrollTop);
async function selectWord(){await frame.locator('.textLayer span').first().evaluate(e=>{const r=document.createRange();r.selectNodeContents(e);const s=getSelection();s.removeAllRanges();s.addRange(r);});}
await selectWord();await frame.locator('body').press('Control+c');await page.locator('[data-work-tab="query"][aria-selected="true"]').waitFor();assert.equal(await page.locator('#query').inputValue(),'navigation');assert(await page.locator('#work-query #browser-grid').isVisible());await page.locator('#work-return').click();assert.equal(await frame.locator('#page').inputValue(),'2');assert.equal(await frame.locator('#zoom').inputValue(),'2');assert.equal(await frame.locator('#scroller').evaluate(e=>e.scrollTop),scroll);
await page.locator('#work-auto').uncheck();await selectWord();await frame.locator('body').press('Control+c');assert.equal(await page.locator('[data-work-tab="query"]').getAttribute('aria-selected'),'false');await selectWord();await frame.locator('.textLayer').dispatchEvent('contextmenu',{clientX:60,clientY:80});await frame.locator('#copy-menu').click();await page.locator('[data-work-tab="query"][aria-selected="true"]').waitFor();await page.locator('#work-return').click();
await frame.locator('#find-text').fill('obscure');await frame.locator('#find-text').press('Enter');await frame.locator('.find-match').filter({hasText:'obscure'}).waitFor();assert.equal(await frame.locator('#page').inputValue(),'1');await page.screenshot({path:'fixtures/ui-v10-work.png'});
await page.locator('#work-files').setInputFiles(file);assert.equal(await page.locator('.work-pdf').count(),2);await page.locator('[data-work-close]').last().click();assert.equal(await page.locator('.work-pdf').count(),1);await page.locator('#work-return').click();await frame.locator('body').evaluate((body,bytes)=>{const transfer=new DataTransfer();transfer.items.add(new File([new Uint8Array(bytes)],'dropped.pdf',{type:'application/pdf'}));body.dispatchEvent(new DragEvent('drop',{dataTransfer:transfer,bubbles:true,cancelable:true}));},[...fs.readFileSync(file)]);await page.locator('[data-work-close]').nth(1).waitFor();assert.equal(await page.locator('.work-pdf').count(),2);await page.locator('[data-work-close]').last().click();await page.locator('[data-page="search"]').click();assert(await page.locator('main > #page-search #query').isVisible());await page.locator('[data-page="work"]').click();assert(await page.locator('#work-query #query').isVisible());assert.deepEqual(errors,[]);console.log('V10 UI PASSED: MW-only review, Cambridge UK/US, PDF rendering/selection/copy/manual lookup/search, tabs, zoom/page/scroll restoration and shared dictionary.');
}finally{if(page&&!page.isClosed())await page.evaluate(()=>{selectionDraft=null;document.querySelectorAll('dialog[open]').forEach(d=>d.close());}).catch(()=>{});await app.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
