const {_electron:electron}=require('playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),cheerio=require('cheerio');
const {Store}=require('../src/store.cjs');
(async()=>{
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-v13-')),store=new Store(path.join(profile,'library'));store.data.groups=['阅读'];store.data.lastCollectionGroups=['阅读'];const entry=JSON.parse(fs.readFileSync('fixtures/go-mw-v3.json'));entry.headword='go';const word=store.collect(entry,['阅读']);word.entries.mw.senses.forEach(s=>s.selected=true);store.save();
const env={...process.env,WORDDESK_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;const launch=()=>electron.launch({args:process.env.WORDDESK_RELEASE?[path.resolve(process.env.WORDDESK_RELEASE)]:['.'],env,timeout:30000});let app=await launch(),page;
try{
page=await app.firstWindow();page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('[data-page="settings"]').click();assert(await page.locator('#auto-select-collect').isChecked());assert.equal(await page.locator('#exam-position').inputValue(),'bottom');
await page.locator('[data-page="exam"]').click();await page.locator('#exam-start').click();const positions=()=>page.evaluate(()=>({progress:document.querySelector('.exam-progress').getBoundingClientRect().y,toolbar:document.querySelector('.exam-toolbar').getBoundingClientRect().y,scroll:document.querySelector('.exam-scroll').getBoundingClientRect().y}));let p=await positions();assert(p.progress<p.scroll&&p.scroll<p.toolbar);await page.locator('#exam-answer').fill('partial');await page.locator('.exam-scroll').evaluate(e=>e.scrollTop=e.scrollHeight);assert(await page.locator('#exam-submit').isVisible());await page.locator('[data-page="settings"]').click();await page.locator('#exam-position').selectOption('top');await page.locator('[data-page="exam"]').click();assert.equal(await page.locator('#exam-answer').inputValue(),'partial');p=await positions();assert(p.progress<p.toolbar&&p.toolbar<p.scroll);await page.locator('#exam-answer').fill('go');await page.locator('#exam-answer').press('Enter');assert.match(await page.locator('#exam-feedback').innerText(),/回答正确/);
const $=cheerio.load(fs.readFileSync('fixtures/plum-mw.html','utf8'));$('script,iframe,link,img,video').remove();$('[data-file]').removeAttr('data-file');await app.evaluate(async({session},html)=>{await session.fromPartition('persist:dictionary-mw').protocol.handle('https',()=>new Response(html,{headers:{'content-type':'text/html'}}));},$.html());await page.locator('[data-page="work"]').click();await app.evaluate(async({webContents,session})=>{await webContents.getAllWebContents().find(w=>w.session===session.fromPartition('persist:dictionary-mw')).loadURL('https://www.merriam-webster.com/dictionary/plum');});await page.locator('[data-quick="mw"]').click();await page.locator('#save-selection').waitFor();assert.equal(await page.locator('[data-select-sense][aria-checked="true"]').count(),0);await page.locator('[data-select-sense="0"]').click();await page.locator('#save-selection').click();await page.locator('#begin-selection').waitFor();await page.locator('[data-work-tab="query"]').click();await page.locator('[data-quick="mw"]').click();await page.locator('#save-selection').waitFor();assert.equal(await page.locator('[data-select-sense="0"]').getAttribute('aria-checked'),'true');await page.locator('#save-selection').click();await page.locator('#begin-selection').waitFor();await page.locator('[data-page="settings"]').click();await page.locator('#auto-select-collect').uncheck();await page.locator('[data-page="work"]').click();await page.locator('[data-work-tab="query"]').click();await page.locator('[data-quick="mw"]').click();await page.locator('.entry-headword').filter({hasText:'plum'}).waitFor();await page.locator('#begin-selection').waitFor();assert.equal(await page.locator('#save-selection').count(),0);
await page.locator('[data-page="export"]').click();assert.deepEqual(await page.locator('[data-field]:checked').evaluateAll(es=>es.map(e=>e.dataset.field)),['word','pos','meaning']);await page.locator('#f-phonetic').check();assert.match(await page.locator('#export-print-hint').innerText(),/较拥挤/);await page.locator('#export-print-preset').click();await page.locator('#export-scope').selectOption('selected');await page.locator('#export-order').selectOption('alpha');const output=path.join(profile,'print.xlsx');await app.evaluate(({dialog},file)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:file});},output);await page.locator('#export-button').click();await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('.xlsx'));assert(fs.statSync(output).size>1000);await page.locator('[data-page="settings"]').click();await page.locator('[data-page="export"]').click();assert.equal(await page.locator('#export-scope').inputValue(),'selected');assert.equal(await page.locator('#export-order').inputValue(),'alpha');await page.screenshot({path:'fixtures/ui-v13-export.png'});assert.deepEqual(errors,[]);
await app.close();app=await launch();page=await app.firstWindow();await page.locator('[data-page="settings"]').click();assert(!(await page.locator('#auto-select-collect').isChecked()));assert.equal(await page.locator('#exam-position').inputValue(),'top');await page.screenshot({path:'fixtures/ui-v13-settings.png'});console.log('V13 UI PASSED: persistent preferences, exam positions/input/Enter, collection auto selection fresh/repeated/off, print preset and export.');
}finally{if(page&&!page.isClosed())await page.evaluate(()=>{selectionDraft=null;document.querySelectorAll('dialog[open]').forEach(d=>d.close());}).catch(()=>{});await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
