const {_electron:electron}=require('playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),cheerio=require('cheerio');
const {Store}=require('../src/store.cjs'),{makePDF}=require('./pdf-test-fixture.cjs');
(async()=>{const profile=fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-v12-')),store=new Store(path.join(profile,'library'));store.data.groups=['阅读'];for(const name of ['obscure','navigation']){for(const source of ['mw','cambridge']){const e=JSON.parse(fs.readFileSync('fixtures/go-'+source+'-v3.json'));e.headword=name;store.collect(e,['阅读']);}}const w=store.data.words[0];w.entries.mw.senses[0].selected=true;store.save();const file=path.join(profile,'book.pdf');fs.writeFileSync(file,makePDF());const env={...process.env,WORDDESK_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;const app=await electron.launch({args:process.env.WORDDESK_RELEASE?[path.resolve(process.env.WORDDESK_RELEASE)]:['.'],env,timeout:30000});let page;
try{page=await app.firstWindow();page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const $=cheerio.load(fs.readFileSync('fixtures/plum-mw.html','utf8'));$('script,iframe,link,img,video').remove();$('[data-file]').removeAttr('data-file');await app.evaluate(async({session},html)=>{for(const s of ['mw','cambridge'])await session.fromPartition('persist:dictionary-'+s).protocol.handle('https',()=>new Response(html,{headers:{'content-type':'text/html'}}));},$.html());

await app.evaluate(async({webContents,session})=>{const wc=webContents.getAllWebContents().find(w=>w.session===session.fromPartition('persist:dictionary-mw'));await wc.loadURL('https://www.merriam-webster.com/dictionary/plum');const original=wc.executeJavaScript.bind(wc);wc.executeJavaScript=async(...args)=>{const result=await original(...args);await new Promise(r=>setTimeout(r,1200));return result;};});
await page.evaluate(()=>{window.pending=collect('mw',['阅读']);});await page.locator('#collection-progress').waitFor();await page.locator('[data-page="settings"]').click();await page.evaluate(()=>window.pending);assert.equal(await page.evaluate(()=>page),'settings');assert(await page.locator('#collection-view').isVisible());
await page.locator('[data-page="search"]').click();await page.evaluate(()=>{window.pending=collect('mw',['阅读']);});await page.locator('[data-page="settings"]').click();await page.locator('[data-page="search"]').click();await page.evaluate(()=>window.pending);assert.equal(await page.evaluate(()=>page),'search');
await page.evaluate(()=>{window.pending=collect('mw',['阅读']);});await page.evaluate(()=>window.pending);assert.equal(await page.evaluate(()=>page),'library');
await page.locator('[data-page="work"]').click();await page.locator('[data-work-tab="query"]').click();await page.evaluate(()=>{window.pending=collect('mw',['阅读']);});await page.locator('[data-work-tab="library"]').click();await page.evaluate(()=>window.pending);assert.equal(await page.evaluate(()=>workTab),'library');assert.equal(await page.evaluate(()=>selectionDraft),null);
await page.locator('#work-files').setInputFiles(file);const frame=page.frameLocator('.work-pdf').first();await frame.locator('.textLayer span').first().waitFor();await page.evaluate(async()=>{const w=data.words.find(w=>w.word==='obscure');for(const source of ['mw','cambridge']){w.entries[source].senses.slice(0,3).forEach(s=>s.selected=true);}await api('update',w);await showPDFPopup(workTab,{text:'obscure'},20,20);});const headings=await page.locator('.popup-pos').allTextContents();assert.equal(headings.length,new Set(headings.map(x=>x.toLowerCase())).size);assert(await page.locator('.popup-sense').count()>=6);assert.deepEqual(errors,[]);console.log('V17 UI PASSED: progress, leave/return no jump, foreground auto-open, work tabs, cross-source grouped POS.');
}catch(e){throw e;}finally{if(page&&!page.isClosed())await page.evaluate(()=>{selectionDraft=null;document.querySelectorAll('dialog[open]').forEach(d=>d.close());}).catch(()=>{});await app.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
