const {_electron:electron}=require('playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {Store}=require('../src/store.cjs'),{rows}=require('../src/export.cjs');
(async()=>{
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-v5-ui-')),store=new Store(path.join(profile,'library'));
 for(const source of ['mw','cambridge'])store.collect(JSON.parse(fs.readFileSync(`fixtures/go-${source}-v3.json`)));
 const w=store.data.words[0],mw=w.entries.mw,cam=w.entries.cambridge;mw.senses[0].selected=true;mw.senses[0].autoTranslation='MW 缓存翻译';cam.senses[0].selected=true;delete cam.senses[0].includeChinese;w.notes='双词典笔记';store.save();
 const env={...process.env,WORDDESK_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;const args=process.env.WORDDESK_RELEASE?[path.resolve(process.env.WORDDESK_RELEASE)]:['.'];let app=await electron.launch({args,env,timeout:30000}),page;
 try{
  page=await app.firstWindow();page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.locator('[data-page="review"]').click();await page.locator('.word-row').click();assert.equal(await page.locator('.review-source').count(),2);assert.equal(await page.locator('.dictionary-definition').count(),2);assert.equal(await page.locator('[data-review-source="cambridge"] .dictionary-chinese').count(),1);
  await page.locator('#view-full').click();assert.equal(await page.locator('[data-source="mw"]').innerText(),'MW');assert.equal(await page.locator('[data-source="cambridge"]').innerText(),'Cam');assert.equal(await page.locator('.selection-bar').count(),0);assert.equal(await page.locator('.word-heading [data-source]').count(),2);assert.equal(await page.locator('.entry-actions #begin-selection').count(),1);
  await page.screenshot({path:'fixtures/ui-v5-library.png'});
  await page.locator('#begin-selection').click();assert.equal(await page.locator('[data-select-sense="0"]').getAttribute('aria-checked'),'true');await page.locator('[data-select-sense="1"]').click();await page.locator('#cancel-selection').click();assert.equal(await page.locator('.saved-sense').count(),1);
  await page.locator('#begin-selection').click();await page.locator('[data-select-sense="1"]').click();await page.locator('#save-selection').click();await page.locator('#begin-selection').waitFor();
  await page.locator('[data-source="cambridge"]').click();await page.locator('#begin-selection').click();assert.equal(await page.locator('[data-select-chinese="0"]').getAttribute('aria-checked'),'true');
  await page.locator('[data-select-sense="1"]').click();assert.equal(await page.locator('[data-select-chinese="1"]').getAttribute('aria-checked'),'false');assert.equal(await page.locator('[data-selection-mode="1"]').innerText(),'仅英文');
  await page.locator('[data-select-chinese="2"]').click();assert.equal(await page.locator('[data-select-sense="2"]').getAttribute('aria-checked'),'true');assert.equal(await page.locator('[data-selection-mode="2"]').innerText(),'中英');
  await page.locator('[data-select-chinese="2"]').click();assert.equal(await page.locator('[data-select-sense="2"]').getAttribute('aria-checked'),'true');assert.equal(await page.locator('[data-select-chinese="2"]').getAttribute('aria-checked'),'false');
  await page.locator('[data-select-chinese="2"]').focus();await page.keyboard.press('Space');await page.locator('[data-select-sense="2"]').click();assert.equal(await page.locator('[data-select-chinese="2"]').getAttribute('aria-checked'),'false');assert.equal(await page.locator('[data-select-sense="2"]').getAttribute('aria-checked'),'false');
  await page.locator('[data-select-chinese="2"]').click();await page.screenshot({path:'fixtures/ui-v5-cam-selection.png'});await page.locator('#save-selection').click();await page.locator('#begin-selection').waitFor();
  await page.locator('#begin-selection').click();assert.equal(await page.locator('[data-select-sense][aria-checked="true"]').count(),3);assert.equal(await page.locator('[data-select-chinese][aria-checked="true"]').count(),2);await page.locator('#cancel-selection').click();
  await page.locator('[data-page="review"]').click();assert.equal(await page.locator('[data-review-source="mw"] .dictionary-definition').count(),2);assert.equal(await page.locator('[data-review-source="cambridge"] .dictionary-definition').count(),3);assert.equal(await page.locator('[data-review-source="cambridge"] [data-sense-index="1"] .dictionary-chinese').count(),0);
  assert.equal(await page.locator('[data-review-source="cambridge"] [data-sense-index="2"] .dictionary-chinese').count(),1);
  // Editing either source in the combined view must not modify the other source at the same index.
  await page.locator('[data-review-source="mw"] [data-translate="0"]').click();assert.match(await page.locator('[data-review-source="mw"] .sense-translation').innerText(),/MW 缓存翻译/);
  await page.locator('[data-review-source="mw"] [data-edit-sense="0"]').click();assert.match(await page.locator('#edit-context').innerText(),/Merriam-Webster/);await page.locator('#edit-definition').fill('MW revised for combined review');await page.locator('#edit-save').click();await page.locator('#edit-dialog').waitFor({state:'hidden'});
  await page.locator('[data-review-source="cambridge"] [data-edit-sense="1"]').click();assert.match(await page.locator('#edit-context').innerText(),/剑桥/);await page.locator('#edit-definition').fill('Cam English-only revised');await page.locator('#edit-save').click();await page.locator('#edit-dialog').waitFor({state:'hidden'});
  let saved=(await page.evaluate(()=>window.desk.invoke('init'))).data.words[0],r=rows([saved],'time')[0];assert.match(r.definition,/MW revised for combined review/);assert.match(r.definition,/Cam English-only revised/);assert.equal(saved.entries.cambridge.senses[0].definition,cam.senses[0].definition);assert(!r.translation.includes(cam.senses[1].translation));assert(r.translation.includes(cam.senses[2].translation));
  await page.screenshot({path:'fixtures/ui-v5-review.png'});
  await page.locator('#view-full').click();await page.locator('[data-source="mw"]').click();await page.locator('#begin-selection').click();assert.equal(await page.locator('[data-select-sense][aria-checked="true"]').count(),2);await page.locator('#select-none').click();await page.locator('[data-source="cambridge"]').click();await page.locator('#selection-dialog button[value="discard"]').click();
  saved=(await page.evaluate(()=>window.desk.invoke('init'))).data.words[0];assert.equal(saved.entries.mw.senses.filter(s=>s.selected).length,2);
  await page.locator('[data-source="mw"]').click();await page.locator('#begin-selection').click();await page.locator('#select-none').click();await page.locator('#save-selection').click();await page.locator('[data-page="review"]').click();assert.equal(await page.locator('[data-review-source="mw"]').count(),0);assert.equal(await page.locator('[data-review-source="cambridge"] .dictionary-definition').count(),3);
  await page.locator('#view-full').click();await page.locator('#begin-selection').click();await page.locator('[data-select-sense="0"]').click();await page.locator('#save-selection').click();await page.locator('[data-page="settings"]').click();await page.locator('[data-theme-choice="dark"]').click();await page.locator('[data-page="review"]').click();await page.screenshot({path:'fixtures/ui-v5-review-dark.png'});
  assert.deepEqual(errors,[]);await app.close();app=await electron.launch({args,env,timeout:30000});page=await app.firstWindow();await page.locator('[data-page="review"]').click();await page.locator('.word-row').click();assert.equal(await page.locator('.review-source').count(),2);assert.equal(await page.locator('.dictionary-definition').count(),4);assert.equal(await page.locator('[data-review-source="cambridge"] .dictionary-chinese').count(),2);
  console.log('V5 UI PASSED: compact controls, legacy bilingual choices, draft preload/cancel, all language toggle transitions, independent source saves, combined review/export/editing, source clear isolation and restart persistence.');
 }finally{if(page&&!page.isClosed())await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());selectionDraft=null;}).catch(()=>{});await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
