const {_electron:electron}=require('playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),cheerio=require('cheerio');
const {Store}=require('../src/store.cjs');
(async()=>{
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-v6-ui-')),store=new Store(path.join(profile,'library'));store.data.groups=['阅读'];
 const w=store.collect(JSON.parse(fs.readFileSync('fixtures/go-mw-v3.json')),['阅读']);store.collect(JSON.parse(fs.readFileSync('fixtures/go-cambridge-v3.json')),['阅读']);w.notes='保留笔记';
 fs.mkdirSync(path.join(store.root,'assets','old'),{recursive:true});fs.writeFileSync(path.join(store.root,'assets/old/page-1.png'),'old screenshot');fs.writeFileSync(path.join(store.root,'assets/old/audio.mp3'),'keep audio');w.entries.mw.snapshot=['assets/old/page-1.png'];store.save();
 const env={...process.env,WORDDESK_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;const args=process.env.WORDDESK_RELEASE?[path.resolve(process.env.WORDDESK_RELEASE)]:['.'];const app=await electron.launch({args,env,timeout:30000});let page;
 try{
  page=await app.firstWindow();page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('[data-page="library"]').click();await page.locator('.word-row').click();
  assert.equal(await page.locator('.group-tags, [data-group], [data-snapshot]').count(),0);assert(await page.locator('#group-filter').isVisible());assert.equal((await page.evaluate(()=>window.desk.invoke('init'))).data.words[0].groups[0],'阅读');
  await page.locator('#begin-selection').click();const last=await page.locator('[data-select-sense]').last().getAttribute('data-select-sense');await page.locator('[data-select-sense]').last().click();
  async function verifyToolbar(){
   const bounds=await page.locator('.entry-toolbar').boundingBox();const content=await page.locator('.entry-scroll').boundingBox();assert(content.y>=bounds.y+bounds.height-1);assert(content.height>80);
   for(const id of ['save-selection','cancel-selection','select-all','select-none','lookup-again','delete-word']){const box=await page.locator('#'+id).boundingBox();assert(box.y>=bounds.y&&box.y+box.height<=bounds.y+bounds.height+1,id);assert(await page.locator('#'+id).isVisible());}
   assert(await page.locator('.entry-scroll').evaluate(e=>e.scrollTop>100));
  }
  await verifyToolbar();await page.screenshot({path:'fixtures/ui-v6-bottom.png'});await page.locator('#save-selection').click();await page.locator('#begin-selection').waitFor();let state=await page.evaluate(()=>window.desk.invoke('init'));assert(state.data.words[0].entries.mw.senses[+last].selected);
  await page.locator('#begin-selection').click();await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1000,680));await page.locator('[data-select-sense]').last().scrollIntoViewIfNeeded();await verifyToolbar();assert(await page.locator('#word-detail').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.screenshot({path:'fixtures/ui-v6-narrow.png'});await page.locator('#cancel-selection').click();
  await page.locator('[data-source="cambridge"]').click();await page.locator('#begin-selection').click();await page.locator('[data-select-chinese]').last().click();await verifyToolbar();await page.locator('#save-selection').click();await page.locator('#begin-selection').waitFor();
  await page.locator('[data-page="settings"]').click();await page.locator('[data-theme-choice="dark"]').click();await page.locator('[data-page="library"]').click();await page.locator('#begin-selection').click();await page.locator('[data-select-sense]').last().scrollIntoViewIfNeeded();await verifyToolbar();await page.screenshot({path:'fixtures/ui-v6-dark.png'});await page.locator('#cancel-selection').click();
  // Stats are read-only; cleanup requires a deliberate confirmation and preserves non-image data.
  await page.locator('[data-page="storage"]').click();assert.match(await page.locator('#screenshot-space').innerText(),/1 张旧截图/);assert(fs.existsSync(path.join(store.root,'assets/old/page-1.png')));
  await page.locator('#clear-screenshots').click();await page.locator('#confirm-dialog button[value="cancel"]').click();assert(fs.existsSync(path.join(store.root,'assets/old/page-1.png')));
  await page.locator('#clear-screenshots').click();await page.locator('#confirm-action').click();await page.locator('#screenshot-space').filter({hasText:'没有可清理'}).waitFor();assert(!fs.existsSync(path.join(store.root,'assets/old/page-1.png')));assert(fs.existsSync(path.join(store.root,'assets/old/audio.mp3')));state=await page.evaluate(()=>window.desk.invoke('init'));assert.equal(state.data.words[0].notes,'保留笔记');assert.deepEqual(state.data.words[0].entries.mw.snapshot,[]);
  // Collect a saved real DOM at its original origin; fail the test if any screenshot capture is attempted.
  const $=cheerio.load(fs.readFileSync('fixtures/plum-mw.html'));$('script,iframe,link,img,video').remove();$('[data-file]').removeAttr('data-file');
  await app.evaluate(async({session,webContents},html)=>{const sessionMW=session.fromPartition('persist:dictionary-mw');await sessionMW.protocol.handle('https',()=>new Response(html,{headers:{'content-type':'text/html'}}));const wc=webContents.getAllWebContents().find(w=>w.session===sessionMW);wc.debugger.attach=()=>{throw new Error('Screenshot capture is forbidden');};await wc.loadURL('https://www.merriam-webster.com/dictionary/plum');},$.html());
  const results=await page.evaluate(()=>window.desk.invoke('collect','mw',['阅读']));assert(!results[0].error,JSON.stringify(results));assert(!results[0].warnings.some(s=>/截图|快照/.test(s)));state=await page.evaluate(()=>window.desk.invoke('init'));const plum=state.data.words.find(w=>w.word==='plum');assert(plum);assert.deepEqual(plum.entries.mw.snapshot,[]);assert.deepEqual(await page.evaluate(()=>window.desk.invoke('screenshotStats')),{count:0,bytes:0});assert.deepEqual(errors,[]);
  console.log('V6 UI PASSED: fixed toolbar at bottom and narrow width, separate scrolling, both source saves, hidden detail groups, no new screenshots, cleanup statistics/cancel/delete and preserved audio/notes.');
 }finally{if(page&&!page.isClosed())await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());selectionDraft=null;}).catch(()=>{});await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
