const {_electron:electron}=require('playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),cheerio=require('cheerio');
const {Store}=require('../src/store.cjs');
(async()=>{
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-v7-ui-')),store=new Store(path.join(profile,'library'));store.data.groups=['阅读','保留'];
 const fixture=s=>JSON.parse(fs.readFileSync('fixtures/go-'+s+'-v3.json'));
 const w=store.collect(fixture('mw'),['阅读','保留']);store.collect(fixture('cambridge'),['阅读']);w.notes='保留笔记';
 fs.mkdirSync(path.join(store.root,'assets'));for(const s of ['mw','cambridge']){fs.writeFileSync(path.join(store.root,'assets',s+'.mp3'),'test');w.entries[s].audio[0].file='assets/'+s+'.mp3';}store.save();
 const env={...process.env,WORDDESK_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;const args=process.env.WORDDESK_RELEASE?[path.resolve(process.env.WORDDESK_RELEASE)]:['.'];const app=await electron.launch({args,env,timeout:30000});let page;
 try{
  page=await app.firstWindow();page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const state=()=>page.evaluate(()=>window.desk.invoke('init'));
  await page.locator('[data-page="library"]').click();await page.locator('.word-row').click();
  const tab=async s=>{await page.locator('[data-source="'+s+'"]').click();await page.locator('[data-source="'+s+'"].active').waitFor();};
  const pick=async()=>{await page.locator('#begin-selection').click();await page.locator('[data-select-sense="0"]').click();await tab('cambridge');assert(await page.locator('#save-selection').isVisible());assert.equal(await page.locator('dialog[open]').count(),0);await page.locator('[data-select-chinese="0"]').click();await page.locator('[data-select-sense="1"]').click();assert.match(await page.locator('#selection-count').innerText(),/MW 已选 1 条 · Cam 已选 2 条/);await tab('mw');assert.equal(await page.locator('[data-select-sense="0"]').getAttribute('aria-checked'),'true');};
  await pick();await page.locator('#cancel-selection').click();let d=(await state()).data.words[0];assert(!d.entries.mw.senses[0].selected);assert(!d.entries.cambridge.senses[0].selected);
  await pick();await tab('cambridge');await page.locator('#save-selection').click();await page.locator('#begin-selection').waitFor();d=(await state()).data.words[0];assert(d.entries.mw.senses[0].selected);assert(d.entries.cambridge.senses[0].includeChinese);assert(d.entries.cambridge.senses[1].selected);assert(!d.entries.cambridge.senses[1].includeChinese);assert.equal(await page.locator('[data-audio],#retry-audio').count(),0);assert(await page.locator('.pronunciation-flow').innerText());
  await page.locator('#begin-selection').click();assert.equal(await page.locator('[data-select-chinese="0"]').getAttribute('aria-checked'),'true');await page.locator('#select-none').click();assert.match(await page.locator('#selection-count').innerText(),/MW 已选 1 条 · Cam 已选 0 条/);await tab('mw');await page.locator('[data-page="review"]').click();await page.locator('#selection-dialog button[value="continue"]').click();assert(await page.locator('#save-selection').isVisible());await page.locator('#cancel-selection').click();await page.locator('[data-page="review"]').click();assert.equal(await page.locator('[data-review-source]').count(),2);assert.equal(await page.locator('[data-review-source="cambridge"] [data-audio]').count(),0);
  await page.locator('[data-page="library"]').click();await page.locator('#group-filter').selectOption('阅读');assert(await page.locator('#delete-group').isVisible());await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1000,680));await page.locator('#begin-selection').click();await page.locator('[data-select-sense]').last().scrollIntoViewIfNeeded();assert(await page.locator('#save-selection').isVisible());assert(await page.locator('#word-detail').evaluate(e=>e.scrollWidth<=e.clientWidth+1));await page.screenshot({path:'fixtures/ui-v7-narrow.png'});await page.locator('#cancel-selection').click();
  await page.locator('#delete-group').click();assert.match(await page.locator('#confirm-message').innerText(),/1 个单词/);await page.locator('#confirm-dialog button[value="cancel"]').click();assert((await state()).data.groups.includes('阅读'));await page.locator('#delete-group').click();await page.locator('#confirm-action').click();await page.locator('#delete-group').waitFor({state:'hidden'});d=(await state()).data;assert.deepEqual(d.groups,['保留']);assert.deepEqual(d.words[0].groups,['保留']);assert.deepEqual(d.lastCollectionGroups,[]);assert.equal(d.words[0].notes,'保留笔记');
  await page.locator('[data-page="storage"]').click();assert.match(await page.locator('#cambridge-audio-space').innerText(),/1/);await page.locator('#clear-cambridge-audio').click();await page.locator('#confirm-dialog button[value="cancel"]').click();assert(fs.existsSync(path.join(store.root,'assets/cambridge.mp3')));await page.locator('#clear-cambridge-audio').click();await page.locator('#confirm-action').click();await page.locator('#cambridge-audio-space').filter({hasText:'没有可清理'}).waitFor();assert(!fs.existsSync(path.join(store.root,'assets/cambridge.mp3')));assert(fs.existsSync(path.join(store.root,'assets/mw.mp3')));
  const $=cheerio.load(fs.readFileSync('fixtures/go-cambridge.html'));$('script,iframe,link,img,video').remove();
  await app.evaluate(async({session,webContents},html)=>{const s=session.fromPartition('persist:dictionary-cambridge');globalThis.camFetches=0;s.fetch=async()=>{globalThis.camFetches++;throw new Error('Cam download forbidden');};await s.protocol.handle('https',()=>new Response(html,{headers:{'content-type':'text/html'}}));await webContents.getAllWebContents().find(w=>w.session===s).loadURL('https://dictionary.cambridge.org/dictionary/english-chinese-simplified/go');},$.html());
  const result=await page.evaluate(()=>window.desk.invoke('collect','cambridge',['保留']));assert(!result[0].error,JSON.stringify(result));assert(!result[0].warnings.some(s=>/音频|录音/.test(s)));assert.equal(await app.evaluate(()=>globalThis.camFetches),0);d=(await state()).data.words[0];assert(d.entries.cambridge.audio.length);assert(d.entries.cambridge.audio.every(a=>!a.file));assert(d.entries.cambridge.senses[0].selected);assert(d.entries.mw.senses[0].selected);assert.deepEqual(errors,[]);
  console.log('V7 UI PASSED: cross-source drafts/save/cancel/preload/current-clear, navigation guard, combined review, narrow fixed toolbar, group deletion/cancel/history, Cambridge cleanup/cancel/MW preservation and zero Cambridge downloads.');
 }finally{if(page&&!page.isClosed())await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());selectionDraft=null;}).catch(()=>{});await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
