const {_electron:electron}=require('playwright'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict');
const {Store}=require('../src/store.cjs');
(async()=>{
 const profile=fs.mkdtempSync(path.join(os.tmpdir(),'worddesk-v9-ui-')),store=new Store(path.join(profile,'library'));store.data.groups=['考试','空'];
 for(const [i,name]of ['alpha','beta','gamma','delta','empty'].entries()){
  let w;for(const source of ['mw','cambridge']){const e=JSON.parse(fs.readFileSync('fixtures/go-'+source+'-v3.json'));e.headword=name;e.senses=e.senses.slice(0,1);Object.assign(e.senses[0],{definition:name+' is a sample word',translation:'中文释义',examples:[{text:'An '+name+' example',translation:'例句',selected:false}]});w=store.collect(e,[name==='empty'?'空':'考试']);w.entries[source].senses[0].selected=name!=='empty';w.entries[source].senses[0].includeChinese=source==='mw';w.entries[source].senses[0].examples[0].selected=true;}
  w.createdAt='2026-09-21T00:00:0'+i+'Z';w.notes='Remember '+name;
 }store.save();const before=JSON.stringify(store.data);
 const env={...process.env,WORDDESK_TEST_DATA:profile};delete env.ELECTRON_RUN_AS_NODE;const args=process.env.WORDDESK_RELEASE?[path.resolve(process.env.WORDDESK_RELEASE)]:['.'];const app=await electron.launch({args,env,timeout:30000});let page;
 try{
  page=await app.firstWindow();page.setDefaultTimeout(15000);const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.locator('[data-page="review"]').click();await page.locator('.word-row').first().click();assert.equal(await page.locator('.review-source-label').count(),0);assert.doesNotMatch(await page.locator('#word-list').innerText(),/MW|Cam/);assert.deepEqual(await page.locator('.entry-actions button').evaluateAll(es=>es.map(e=>e.id)),['toggle-review-phonetics','view-full','delete-word']);
  await page.locator('[data-page="exam"]').click();assert.match(await page.locator('#exam-eligible').innerText(),/4 个单词；1 个/);await page.locator('#exam-group').selectOption('空');assert(await page.locator('#exam-start').isDisabled());await page.locator('#exam-group').selectOption('考试');await page.locator('#exam-start').click();
  const answer=page.locator('#exam-answer');assert(await answer.evaluate(e=>e===document.activeElement));assert.doesNotMatch(await page.locator('#exam-content').innerText(),/alpha|MW|Cam|中文释义/);assert.equal(await page.locator('#exam-content .inline-edit,#exam-content .inline-translate,#exam-content .pronunciation-flow').count(),0);assert.match(await page.locator('#exam-content').innerText(),/______/);assert.equal(await page.locator('#exam-content details[open]').count(),0);
  await answer.press('Enter');assert.match(await page.locator('#exam-feedback').innerText(),/请先输入/);assert.equal(await page.evaluate(()=>examResult().attempts),0);
  await answer.fill('alpha');await answer.dispatchEvent('compositionstart');await answer.press('Enter');assert.equal(await page.evaluate(()=>examResult().attempts),0);await answer.dispatchEvent('compositionend');await page.waitForTimeout(100);await answer.fill(' ALPHA ');await answer.press('Enter');assert.match(await page.locator('#exam-feedback').innerText(),/回答正确/);assert.match(await page.locator('.exam-progress').innerText(),/第 1/);await answer.press('Enter');assert.match(await page.locator('.exam-progress').innerText(),/第 2/);
  await answer.fill('wrong');await answer.press('Enter');assert.equal(await answer.inputValue(),'wrong');assert.match(await page.locator('#exam-feedback').innerText(),/拼写不正确/);assert.doesNotMatch(await page.locator('#exam-content').innerText(),/beta/);await answer.fill('beta');await answer.press('Enter');await answer.press('Enter');
  await page.locator('#exam-phonetics').click();assert.match(await page.locator('#exam-hint-status').innerText(),/提示/);assert.equal(await page.locator('#exam-content .pronunciation-flow').count(),1);await page.locator('#exam-reveal').click();assert.match(await page.locator('#exam-feedback').innerText(),/gamma/);await answer.press('Enter');assert.equal(await page.locator('#exam-content .pronunciation-flow').count(),0);
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(1000,680));await page.screenshot({path:'fixtures/ui-v9-exam.png'});await page.locator('#exam-skip').click();assert.match(await page.locator('.exam-summary').innerText(),/首次答对/);assert.deepEqual(await page.evaluate(()=>Exam.examStats(examSession.results)),{firstCorrect:1,wrong:1,revealed:1,skipped:1,hinted:1});assert.match(await page.locator('#exam-retry').innerText(),/3/);await page.locator('#exam-retry').click();assert.match(await page.locator('.exam-progress').innerText(),/第 1 \/ 3/);
  await page.locator('#exam-content .exam-hint summary').first().click();await page.locator('#exam-hint-status').filter({hasText:'提示'}).waitFor();assert.match(await page.locator('#exam-hint-status').innerText(),/提示/);await answer.fill('partial');await page.locator('[data-page="settings"]').click();await page.locator('[data-theme-choice="dark"]').click();await page.locator('[data-page="exam"]').click();assert.equal(await answer.inputValue(),'partial');await page.screenshot({path:'fixtures/ui-v9-exam-dark.png'});await page.locator('#exam-end').click();await page.locator('#confirm-dialog button[value="cancel"]').click();assert(await answer.isVisible());await page.locator('#exam-end').click();await page.locator('#confirm-action').click();await page.locator('.exam-summary').waitFor();assert.equal(await page.evaluate(()=>Exam.examStats(examSession.results).skipped),3);await page.locator('#exam-reset').click();assert(await page.locator('#exam-start').isVisible());
  assert.equal(JSON.stringify((await page.evaluate(()=>window.desk.invoke('init'))).data),before);assert.deepEqual(errors,[]);
  console.log('V9 UI PASSED: review controls/source hiding, exam scope/omission/masking, IME/empty/correct/retry/Enter, hints/reveal/skip/statistics/repractice, resume/end, narrow/dark UI, original data unchanged.');
 }finally{if(page&&!page.isClosed())await page.evaluate(()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());selectionDraft=null;}).catch(()=>{});await app.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
